spring:
  application:
    name: exchange
  config:
    import: "consul:"
  cloud:
    consul:
      retry:
        enabled: true
        max-attempts: 10
        max-interval: 5000
      host: consul
      port: 8500
      discovery:
        service-name: exchange-service
      config:
        enabled: true
        prefixes:
          - config/common
          - config/exchange
        default-context: 'application'
        data-key: ''