apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exchange-generator-service.fullname" . }}
type: Opaque
data:
  spring_security_oauth2_client_registration_exchange-generator-service_client-secret: {{ .Values.secret.oauth2ClientSecret | b64enc | quote }}