pipeline {
    agent any

    environment {
        GRADLE_PATH = './gradlew'
        BUILD_FLAGS = ' '
        IMAGE_TAG = 'latest'
        HELM_RELEASE = 'bankapp'
        CHART_PATH = './bankapp-chart/charts/transfer-service'
        MODULE_NAME = 'transfer-module'
        HELM_NAMESPACE = 'default'
        SERVICE_NAME = 'transfer-service'
    }

    stages {
        stage('Clone repo') {
            steps {
                git 'https://github.com/yungdanie/bankapp.git'
            }
        }

        stage('Build') {
            steps {
                sh "${GRADLE_PATH} build ${BUILD_FLAGS}"
            }
        }

        stage('Build image') {
            steps {
                dir("${MODULE_NAME}") {
                    docker.build("${SERVICE_NAME}:${IMAGE_TAG}")
                }
            }
        }

        stage('Helm dependencies update') {
            steps {
                sh "helm helm dependency update ${CHART_PATH}"
            }
        }

        stage('Helm Upgrade') {
             steps {
                 sh '''
                     helm upgrade --install ${HELM_RELEASE} ${CHART_PATH} \
                         --namespace ${HELM_NAMESPACE} \
                         --create-namespace \
                         --set image.tag=${IMAGE_TAG}
                 '''
             }
        }
    }
}