apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker-service.fullname" . }}
data:
  spring_security_oauth2_resourceserver_jwt_issuer-uri: {{ .Values.config.oauth2.issuerUri | quote }}
  spring_security_oauth2_resourceserver_jwt_jwk-set-uri: {{ .Values.config.oauth2.jwtSetUri | quote }}
