spring:
  config:
    import: "optional:consul:"
  application:
    name: transfer
  cloud:
    consul:
      retry:
        enabled: true
        max-attempts: 10
        max-interval: 5000
      host: consul
      port: 8500
      discovery:
        service-name: transfer-service
      config:
        enabled: true
        prefixes:
          - config/common
          - config/transfer
        default-context: 'application'
        data-key: ''