spring:
  application:
    name: bankui
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: bankui-service
      config:
        enabled: true
        prefixes:
          - config/common
          - config/bankui
        default-context: 'application'
        data-key: ''