apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-env
data:
  ENV: {{ .Values.global.environmentTag | quote }}
  LOGS_TOPIC: {{ .Values.global.logsTopic | quote }}
  KAFKA_BOOTSTRAP: {{ .Values.global.kafkaServers | quote }}
  ES_HOSTS: {{ .Values.global.esHost | quote }}