spring:
  application:
    name: exchange-generator
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 20000
        request.timeout.ms: 10000
        retry.backoff.ms: 200